source 'https://rubygems.org'

gem 'cucumber', '~> 3'
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.7"
gem 'allure-cucumber'
gem "httparty"
gem "faker"
gem "http"
gem "rspec"
gem "redis"
gem "logger"
gem "logging"
gem "aws-sdk-secretsmanager"
gem "aws-sdk-dynamodb"
gem "aws-sdk-lambda"
gem "aws-sdk-sqs"
gem "aws-sdk-cloudformation"
gem "aws-sdk-s3"
gem "aws-sdk-batch"
gem "aws-sdk-cloudwatchlogs"
gem "aws-sdk-cloudwatchevents"
gem "cpf_faker"
gem "pg"
gem "websocket-driver"
gem "websocket-extensions"
gem "json_matchers"
gem "json-schema-rspec"
gem "rspec-json_expectations"
gem "json-schema"
gem "philter"
gem "base64"
gem "ruby-kafka"
gem "rmagick"
gem "pry"
gem "qa_services", git: "git@github.com:dock-tech/services-qa-ruby-lib.git", branch: "master", submodules: true
